### ISSUE TITLE
testing yields MessageFailures by the gallon

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#311]
Bunch of MessageFailure errors while running `python manage.py test`. Not sure if this is from new code and should be ignored, or if this means all kinds of things will not run correctly.

I'm guessing someone forgot to add this to reqs: "django.contrib.messages.middleware.MessageMiddleware"?

Here's one for example:
```
ERROR:django.request:Internal Server Error: /add/error/
Traceback (most recent call last):
  File "/var/www/karmaworld/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/karmaworld/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/karmaworld/venv/local/lib/python2.7/site-packages/django/contrib/messages/tests/urls.py", line 30, in add
    getattr(messages, message_type)(request, msg)
  File "/var/www/karmaworld/venv/local/lib/python2.7/site-packages/django/contrib/messages/api.py", line 102, in error
    fail_silently=fail_silently)
  File "/var/www/karmaworld/venv/local/lib/python2.7/site-packages/django/contrib/messages/api.py", line 22, in add_message
    raise MessageFailure('You cannot add messages without installing '
MessageFailure: You cannot add messages without installing django.contrib.messages.middleware.MessageMiddleware
```

**Comment by btbonval** [comment]
This is still a problem for me, a year later, and with a new environment. @yourcelf updated tests, but I cannot run them. I'm reopening this ticket.

Additionally, we don't have testing documented in the README, which would be good to toss in somewhere. Make sure the environment works before deploying sort of thing.

This is my `manage.py help` output (look for south/test and django-nose/test):
```
Available subcommands:

[account]
    account_emailconfirmationmigration
    account_unsetmultipleprimaryemails

[auth]
    changepassword
    createsuperuser

[compressor]
    compress
    mtime_cache

[courses]
    dump_json
    fetch_usde_csv
    fix_note_counts
    import_json
    import_usde_csv
    sanitize_usde_schools

[django]
    cleanup 
    compilemessages
    createcachetable
    dbshell 
    diffsettings
    dumpdata
    flush   
    inspectdb
    loaddata
    makemessages
    runfcgi 
    shell   
    sql
    sqlall  
    sqlclear
    sqlcustom
    sqlflush
    sqlindexes
    sqlinitialdata
    sqlsequencereset
    startapp
    startproject
    validate

[djcelery]
    camqadm 
    celery  
    celerybeat
    celerycam
    celeryctl
    celeryd 
    celeryd_detach
    celeryd_multi
    celeryev
    celerymon
    djcelerymon

[gunicorn]
    run_gunicorn

[notes]
    add_canonical_link
    convert_notes_to_markdown
    import_ocw_json
    populate_filepicker
    populate_indexden
    regen_note_slugs
    strip_html_to_text
    tweet_note

[quizzes]
    get_mturk_results

[reversion]
    createinitialrevisions
    deleterevisions

[sessions]
    clearsessions

[south]
    convert_to_south
    datamigration
    graphmigrations
    migrate 
    migrationcheck
    schemamigration
    startmigration
    syncdb  
    test
    testserver

[staticfiles]
    collectstatic
    findstatic
    runserver
```
