### ISSUE TITLE
celery error processing uploads

### ISSUE THREAD

**Issue by btbonval** [FinalsClub/karmaworld#387]
Spotted numerous times on the beta system.
```
[2015-01-09 19:28:09,377: WARNING/PoolWorker-4] downloaded!
[2015-01-09 19:28:09,502: ERROR/MainProcess] karmaworld.apps.document_upload.tasks.process_raw_document[19475204-7750-4f1a-9201-f0d3b2753580]: Traceback (most recent call last):
  File "/app/karmaworld/apps/document_upload/tasks.py", line 16, in process_raw_document
    convert_raw_document(raw_document, user=user)
  File "/app/karmaworld/apps/notes/gdrive.py", line 208, in convert_raw_document
    note = raw_document.convert_to_note()
  File "/app/karmaworld/apps/document_upload/models.py", line 63, in convert_to_note
    note.save()
  File "/app/karmaworld/apps/notes/models.py", line 416, in save
    self._update_parent_updated_at()
  File "/app/karmaworld/apps/notes/models.py", line 412, in _update_parent_updated_at
    self.course.save()
  File "/app/karmaworld/apps/courses/models.py", line 298, in save
    super(Course, self).save(*args, **kwargs) # generate a self.id
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 654, in save_base
    transaction.commit_unless_managed(using=using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py", line 134, in commit_unless_managed
    connection.commit_unless_managed()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/__init__.py", line 221, in commit_unless_managed
    self._commit()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 242, in _commit
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 240, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "courses_course" violates foreign key constraint "department_id_refs_id_13ee8a70812efec8"
DETAIL:  Key (department_id)=(10) is not present in table "courses_department".
```

**Comment by btbonval** [comment]
Problem was not obviously present running it again a short while later. Unsure if it was covered by other errors or if it resolved itself.

**Comment by btbonval** [comment]
Still a problem.

**Comment by btbonval** [comment]
Still a problem.

```
[2015-01-13 14:41:32,956: WARNING/PoolWorker-4] text -- https://docs.google.com/feeds/download/documents/export/Export?id=1PR59yThf_UU-5ABzk67hFiOZM9Bpp2T3qt8BxB9E20U&exportFormat=txt
[2015-01-13 14:41:33,182: WARNING/PoolWorker-4] downloaded!
[2015-01-13 14:41:33,187: WARNING/PoolWorker-4] html -- https://docs.google.com/feeds/download/documents/export/Export?id=1PR59yThf_UU-5ABzk67hFiOZM9Bpp2T3qt8BxB9E20U&exportFormat=html
[2015-01-13 14:41:33,365: WARNING/PoolWorker-4] downloaded!
[2015-01-13 14:41:33,510: ERROR/MainProcess] karmaworld.apps.document_upload.tasks.process_raw_document[8fac3ba8-5ea8-419c-ae97-01d7d3dc754e]: Traceback (most recent call last):
  File "/app/karmaworld/apps/document_upload/tasks.py", line 16, in process_raw_document
    convert_raw_document(raw_document, user=user)
  File "/app/karmaworld/apps/notes/gdrive.py", line 208, in convert_raw_document
    note = raw_document.convert_to_note()
  File "/app/karmaworld/apps/document_upload/models.py", line 63, in convert_to_note
    note.save()
  File "/app/karmaworld/apps/notes/models.py", line 416, in save
    self._update_parent_updated_at()
  File "/app/karmaworld/apps/notes/models.py", line 412, in _update_parent_updated_at
    self.course.save()
  File "/app/karmaworld/apps/courses/models.py", line 298, in save
    super(Course, self).save(*args, **kwargs) # generate a self.id
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 654, in save_base
    transaction.commit_unless_managed(using=using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py", line 134, in commit_unless_managed
    connection.commit_unless_managed()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/__init__.py", line 221, in commit_unless_managed
    self._commit()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 242, in _commit
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 240, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "courses_course" violates foreign key constraint "department_id_refs_id_13ee8a70812efec8"
DETAIL:  Key (department_id)=(10) is not present in table "courses_department".
```
